### ISSUE TITLE
FindSlicer.cmake error

### ISSUE THREAD

**Issue by johnwog** [vmtk/SlicerExtension-VMTK#1]
Hi 
I am trying to install the VMTK slicer extension on Yosemite and I keep getting the following error

  By not providing "FindSlicer.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Slicer", but
  CMake did not find one.

  Could not find a package configuration file provided by "Slicer" with any
  of the following names:

```
SlicerConfig.cmake
slicer-config.cmake
```

  Add the installation prefix of "Slicer" to CMAKE_PREFIX_PATH or set
  "Slicer_DIR" to a directory containing one of the above files.  If "Slicer"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by pieper** [comment]
Unfortunately this extension hasn't been working for a while although I thought it would build but not package.  I don't think it has been touched since Yosemite came out.  I suspect it needs to be updated to the latest Extension template from the slicer distribution.

**Comment by rdsouza10** [comment]
Hi, 
I'm on Windows 7, and I get the same error. Is the extension supposed to work on this OS? I'd like to know, so I can figure out if I am doing something wrong. 

Using cmakegui i get the error above.
 If i try the following command in git bash :
cmake -DSlicer_DIR:PATH=$SLICER_BUILD_DIR/Slicer-build ../SlicerExtension-VMTK 

I get this error : 
sh.exe": cmake: command not found  

Any help is appreciated. 

Thanks

**Comment by jcfr** [comment]
Hi,

More work is required to update the extension so that it supported VTKv6.
See
http://slicer-users.65878.n3.nabble.com/Vessel-segmentation-from-CT-images-tp4028900p4028926.html

Hth
Jc

On Thu, May 7, 2015 at 11:55 AM, rdsouza10 <notifications@github.com> wrote:

> Hi,
> I'm on Windows 7, and I get the same error. Is the extension supposed to
> work on this OS? I'd like to know, so I can figure out if I am doing
> something wrong.
>
> Using cmakegui i get the error above.
> If i try the following command in git bash :
> cmake -DSlicer_DIR:PATH=$SLICER_BUILD_DIR/Slicer-build
> ../SlicerExtension-VMTK
>
> I get this error :
> sh.exe": cmake: command not found
>
> Any help is appreciated.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmtk/SlicerExtension-VMTK/issues/1#issuecomment-99920835>
> .
>



-- 
+1 919 869 8849

**Comment by lassoan** [comment]
VMTK extension is built correctly now using nightly and stable Slicer versions.
