### ISSUE TITLE
Concerns about how to detect all endpoints automatically

### ISSUE THREAD

**Issue by Puzzled-Hui** [vmtk/SlicerExtension-VMTK#100]
Thanks for the excellent project!

I have one concern about detecting all endpoints automatically.

It is not clear to me how this step be completed. May you do me a favor to teach me the underlying theory about detecting all endpoints automatically?

Thanks for checking this message, looking forward to your kindful reply.

Best,

**Comment by lassoan** [comment]
You can use network extraction results as endpoints.
