### ISSUE TITLE
Principle of the endpoint detection

### ISSUE THREAD

**Issue by Puzzled-Hui** [vmtk/SlicerExtension-VMTK#101]
You can use network extraction results as endpoints.

_Originally posted by @lassoan in https://github.com/vmtk/SlicerExtension-VMTK/issues/100#issuecomment-1752050937_
            Thank you for the kindful reply!

However, I wonder know that the underlying principle to determine the endpoints?

**Comment by lassoan** [comment]
You can read [Luca Antigua's PhD thesis](https://lantiga.github.io/media/AntigaPhDThesis.pdf) for details.

Please use the [Slicer forum](https://discourse.slicer.org) for asking questions about this extension. The bugtracker is for tracking problems.
