### ISSUE TITLE
CrossSectionAnalysis cannot work on MacOS

### ISSUE THREAD

**Issue by wenrancai** [vmtk/SlicerExtension-VMTK#103]
I am using the latest version of VMTK (2023-9-27) on MacOS. It seems the python script cannot find the C++ lib as the error below. However, for the latest version of VMTK (2023-8-22) on Windows, it works fine.

https://github.com/vmtk/SlicerExtension-VMTK/blame/144582e99404ab97d6126888bf14ebfd4af0b352/CrossSectionAnalysis/CrossSectionAnalysis.py#L995

```
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-31938/SlicerVMTK/lib/Slicer-5.4/qt-scripted-modules/CrossSectionAnalysis.py", line 342, in onApplyButton
    self.logic.run()
  File "/Applications/Slicer.app/Contents/Extensions-31938/SlicerVMTK/lib/Slicer-5.4/qt-scripted-modules/CrossSectionAnalysis.py", line 871, in run
    self.updateOutputTable(self.inputCenterlineNode, self.outputTableNode)
  File "/Applications/Slicer.app/Contents/Extensions-31938/SlicerVMTK/lib/Slicer-5.4/qt-scripted-modules/CrossSectionAnalysis.py", line 995, in updateOutputTable
    import vtkSlicerCrossSectionAnalysisModuleLogicPython as vtkSlicerCrossSectionAnalysisModuleLogic
ImportError: Failed to load vtkSlicerCrossSectionAnalysisModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython
```

**Comment by lassoan** [comment]
Only the latest Slicer Stable Release and latest Slicer Preview Release are supported versions. We do not investigate any issues in any other Slicer versions (such as the older Slicer Preview Release 2023-09-27).

**Comment by wenrancai** [comment]
> Only the latest Slicer Stable Release and latest Slicer Preview Release are supported versions. We do not investigate any issues in any other Slicer versions (such as the older Slicer Preview Release 2023-09-27).

144582e (2023-09-27) is the latest version of SlicerVMTK I can download on Slicer 5.4.0 (latest Slicer Stable Release). The date is shown on the extensions manager.

**Comment by lassoan** [comment]
Thanks for the clarification, I'll have a look.

**Comment by lassoan** [comment]
There have been related fixes. Can you still reproduce the issue in the latest Slicer Preview Release?

**Comment by wenrancai** [comment]
> There have been related fixes. Can you still reproduce the issue in the latest Slicer Preview Release?

Great. It works well now.
