### ISSUE TITLE
Slicer extension packaging fails on MacOSX

### ISSUE THREAD

**Issue by lassoan** [vmtk/SlicerExtension-VMTK#11]
See https://discourse.slicer.org/t/vmtk-vessel-filtering-not-working/1263/7

**Comment by lassoan** [comment]
@jcfr it would be great if you could have a look at this

**Comment by lassoan** [comment]
It seems that VMTK build got broke on Mac on 2017-10-19 due to a change in how 3rd party libs are fixed up.
- Slicer 26481: [OK](http://slicer.cdash.org/index.php?project=Slicer4&date=2017-10-17&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=VMTK)
- Slicer 26493: [failed on Mac](http://slicer.cdash.org/index.php?project=Slicer4&date=2017-10-19&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=VMTK)

@jcfr, could you have a look?

**Comment by mschumak** [comment]
Pull request https://github.com/vmtk/SlicerExtension-VMTK/pull/14 is intended to address this.

**Comment by mschumak** [comment]
This issue can be closed.
