### ISSUE TITLE
SlicerVMTK installation error

### ISSUE THREAD

**Issue by dengwuyong** [vmtk/SlicerExtension-VMTK#116]
The following error occurs after SclierVMTK is installed:
RuntimeError: qSlicerScriptedLoadableModule::setPythonSource - Failed to load scripted loadable module: class vtkvmtk was not found in file C:/ProgramData/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/SlicerVMTK/lib/Slicer-4.11/qt-loadable-modules/vtkvmtk.py

**Comment by lassoan** [comment]
This is already tracked in #22
