### ISSUE TITLE
Improving VMTK Slicer Extension

### ISSUE THREAD

**Issue by rlizzo** [vmtk/SlicerExtension-VMTK#12]
Hey @lassoan, 

I'm wondering if you have some time to talk with me and @lantiga in the next few weeks in regards to the state of the VMTK Slicer Extension? We're pushing out the 1.4 release in the next day or two, and believe that it's an appropriate time to take a look at improving the functionality of the Slicer Extension. (It's a bit anemic compared to the functionality that the full VMTK library allows). 

If you have the time, I'd love to catch up via video-chat. I'm in the US on the EST timezone (GMT -5), but am fairly flexible and can schedule a call around your availability. 

Let me know at your convenience. Thanks!
Rick Izzo

**Comment by lassoan** [comment]
Yes, sure. It would be awesome to expose more features of VMTK in Slicer! I'm in the same time zone. My week is pretty open. Would Wednesday 10am or 2pm or Thursday 10am work for you?

**Comment by lantiga** [comment]
Hi @lassoan! Thursday 10am works for me. Looking forward to our chat.

**Comment by rlizzo** [comment]
Thursday at 10 it is then. I'll send a calendar invite with a link to a Google Hangouts chat. Looking forward to it!

**Comment by lantiga** [comment]
Hi @rlizzo and @lassoan, would it be possible for you to start our call 15 mins earlier? A work-related call got postponed from 9 to 10, so at least I'd be able to join our call for the initial part. Sorry about that!

**Comment by rlizzo** [comment]
I can be available.

**Comment by rlizzo** [comment]
So thank you very much for all you time the other Day @lassoan! 

Both myself and Luca are looking forward to working on a more full featured 3D Slicer extension over the next few months. We think the next step forward will be to map out exactly which VMTK modules depend on image orientation, and begin to construct a work around for it. 

If you'd like, I'll be sure to keep you in the loop over the next few weeks as we scope out the project and begin to understand how it works. Once we get a better feel for the project, I'm sure it would be helpful to schedule another video call and run our plan by you.

**Comment by lassoan** [comment]
Closing the issue, no follow-up tasks are planned for this right now.
