### ISSUE TITLE
Slicer extension fails on MacOS

### ISSUE THREAD

**Issue by mschumak** [vmtk/SlicerExtension-VMTK#16]
This issue may be similar to the previous issue https://github.com/vmtk/SlicerExtension-VMTK/issues/11 with building and packaging the Slicer extension for MacOS. The extension currently fails to build/package on MacOS. 
Before the move from Slicer 4.8 to 4.10, Oct 17, SlicerVMTK could build with MacOS, but not the others: http://slicer.cdash.org/index.php?project=Slicer4&date=2018-10-17&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=vmtk
Problems building for all OS for Slicer 4.10 from Oct 18 to Nov 5, then only build errors for MacOS: http://slicer.cdash.org/index.php?project=Slicer4&date=2018-11-06&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=vmtk

**Comment by lassoan** [comment]
This should fix the problem: https://github.com/vmtk/SlicerExtension-VMTK/pull/17#issuecomment-511131516
