### ISSUE TITLE
Failed to load the extension

### ISSUE THREAD

**Issue by haichaoyu** [vmtk/SlicerExtension-VMTK#21]
Slicer version: 4.10.2
VMTK extension version: May 16, 2019.

Here is the error log:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/13211825/93690255-eeb5fb00-fa9b-11ea-90e7-60525c59da22.png">

**Comment by lassoan** [comment]
Please use latest Slicer-4.11 version and let us know if you run into any issues.

**Comment by haichaoyu** [comment]
@lassoan Thanks. I tried 4.11, there are multiple errors with print function in /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site.py. I guess it is caused by Python version mismatch. The default python in MacOS 10.15.5 is Python 2.7. It seems the scripts only support Python 3. Is there any workaround except unsafely change the default Python?

**Comment by lassoan** [comment]
System Python version does not matter. Slicer does not use it and there should not be any conflicts. It seems that the error is a Mac-specific packaging issue (rpath is not fixed up). Until we fix it, you can use the Linux or Windows version.

**Comment by lassoan** [comment]
I've just tried Slicer-4.11.0-2020-09-08 on Mac and it works perfectly. Which version did you have problem with? Did you pip_installed any packages in Slicer's Python environment? Did you start Slicer from an activated Python virtual environment? Could you copy-paste the complete application log (menu: Help / Report a bug)?

**Comment by haichaoyu** [comment]
I did not install any package in Slicer's Python. I start Slicer by clicking the icon.

Here is the log.

[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Session start time .......: 2020-09-20 00:53:19
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Slicer version ...........: 4.11.0-2020-09-18 (revision 29379 / f54de33) macosx-amd64 - installed release
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Operating system .........: Mac OS X / 10.15.5 / 19F101 - 64-bit
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Memory ...................: 16384 MB physical, 3072 MB virtual
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - CPU ......................: GenuineIntel Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz, 4 cores, 8 logical processors
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, Sequential threading
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Qt configuration .........: version 5.15.0, with SSL, requested OpenGL 3.2 (core profile)
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Developer mode enabled ...: no
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Application path .........: /Applications/Slicer.app/Contents/MacOS
[DEBUG][Qt] 20.09.2020 00:53:19 [] (unknown:0) - Additional module paths ..: /Applications/Slicer.app/Contents/Extensions-29379/SlicerVMTK/lib/Slicer-4.11/qt-loadable-modules, /Applications/Slicer.app/Contents/Extensions-29379/SlicerVMTK/lib/Slicer-4.11/qt-scripted-modules
[DEBUG][Python] 20.09.2020 00:53:20 [Python] (/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pydicom/datadict.py:432) - Reversing DICOM dictionary so can look up tag from a keyword...
[CRITICAL][Qt] 20.09.2020 00:53:20 [] (unknown:0) -   Error(s):
    CLI executable: /Applications/Slicer.app/Contents/Extensions-29379/SlicerVMTK/lib/Slicer-4.11/qt-loadable-modules/vtkvmtk.py
      File "/Applications/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/site.py", line 177
    print("Error processing line {} of {}:\n".format(n+1, fullname), file=sys.stderr)
                                                                         ^
SyntaxError: invalid syntax

    CLI executable: /Applications/Slicer.app/Contents/Extensions-29379/SlicerVMTK/lib/Slicer-4.11/qt-loadable-modules/vtkvmtk.py
    Failed to retrieve Xml Description
[CRITICAL][Qt] 20.09.2020 00:53:20 [] (unknown:0) - Fail to instantiate module  "vtkvmtk"
[CRITICAL][Qt] 20.09.2020 00:53:20 [] (unknown:0) - The following modules failed to be instantiated:
[CRITICAL][Qt] 20.09.2020 00:53:20 [] (unknown:0) -    vtkvmtk
[DEBUG][Python] 20.09.2020 00:53:21 [Python] (/Applications/Slicer.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 20.09.2020 00:53:21 [Python] (/Applications/Slicer.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 20.09.2020 00:53:21 [Python] (/Applications/Slicer.app/Contents/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 20.09.2020 00:53:22 [] (unknown:0) - Switch to module:  "Welcome"
[INFO][VTK] 20.09.2020 00:53:22 [vtkMRMLScene (0x7fb19193c370)] (/Volumes/D/P/S-0/Libs/MRML/Core/vtkMRMLScene.cxx:316) - vtkMRMLScene::Clear
[INFO][VTK] 20.09.2020 00:53:22 [vtkMRMLScene (0x7fb19193c370)] (/Volumes/D/P/S-0/Libs/MRML/Core/vtkMRMLScene.cxx:762) - vtkMRMLScene::Import
[INFO][VTK] 20.09.2020 00:53:22 [vtkMRMLVolumeArchetypeStorageNode (0x7fb190981130)] (/Volumes/D/P/S-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx:473) - Loaded volume from file: /Applications/Slicer.app/Contents/Extensions-29379/SlicerVMTK/lib/Slicer-4.11/qt-scripted-modules/Resources/Vesselness.png. Dimensions: 65x50x1. Number of components: 3. Pixel type: unsigned char.
[INFO][VTK] 20.09.2020 00:53:22 [vtkMRMLScene (0x7fb18ef64700)] (/Volumes/D/P/S-0/Libs/MRML/Core/vtkMRMLScene.cxx:316) - vtkMRMLScene::Clear
[INFO][VTK] 20.09.2020 00:53:22 [vtkMRMLScene (0x7fb18ef64700)] (/Volumes/D/P/S-0/Libs/MRML/Core/vtkMRMLScene.cxx:762) - vtkMRMLScene::Import
[INFO][VTK] 20.09.2020 00:53:22 [vtkMRMLScene (0x7fb19193c370)] (/Volumes/D/P/S-0/Libs/MRML/Core/vtkMRMLScene.cxx:316) - vtkMRMLScene::Clear

**Comment by lassoan** [comment]
I've installed the same 4.11.0-2020-09-18 version and compared the logs.

I've checked error message and it should be harmless:

```
[DEBUG][Python] 20.09.2020 00:53:20 [Python] (/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pydicom/datadict.py:432) - Reversing DICOM dictionary so can look up tag from a keyword...
[CRITICAL][Qt] 20.09.2020 00:53:20 [] (unknown:0) - Error(s):
CLI executable: /Applications/Slicer.app/Contents/Extensions-29379/SlicerVMTK/lib/Slicer-4.11/qt-loadable-modules/vtkvmtk.py
File "/Applications/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/site.py", line 177
print("Error processing line {} of {}:\n".format(n+1, fullname), file=sys.stderr)
```

The reason for the error is that vtkvmtk.py file is an unnecessarily placed in a folder where Slicer looks for modules (this is a bug that should be fixed to avoid error messages but should not cause any issues). The vtkvmtk.py file is not necessary there and should be just ignored. It is OK that the process is failed to be executed.

Can you try to use Extract Centerline module and see if it works well or if you see any additional errors in the log?

**Comment by haichaoyu** [comment]
In my case, VMTK cannot be launched successfully. And thus there is no Extract Centerline module under Segment Editor.

**Comment by lassoan** [comment]
These modules are not Segment Editor effects, so they do not show up in Segment Editor but in the module menu (Vascular Modeling Toolkit category).

**Comment by haichaoyu** [comment]
It works. Thanks!

**Comment by lassoan** [comment]
Great!
