### ISSUE TITLE
VMTK Extension Not Building

### ISSUE THREAD

**Issue by cianciulla** [vmtk/SlicerExtension-VMTK#25]
I downloaded today's nightly Slicer nightly build for Mac (4/12) and I noticed that the VMTK extension is not building.

**Comment by lassoan** [comment]
Thanks for reporting. @jcfr is working on it.

**Comment by lassoan** [comment]
@jcfr do you have any updates? Any hints about how to go about this would help us to get started.

The error message is:

```
  The new name for the 'vtkIOImage' component is 'IOImage'.  By requesting at
  least version 8.90, the new component names are now required.
Call Stack (most recent call first):
  /work/Preview/Slicer-0-build/VTK-build/vtk-config.cmake:1 (include)
  vtkVmtk/Utilities/vtkvmtkITK/CMakeLists.txt:12 (find_package)
```

It may need just similar fixes as done in Slicer core:

https://github.com/Slicer/Slicer/blob/0daa3b92680706c1e98b6585a676545f41c0b8a2/CMakeLists.txt#L508-L545

**Comment by lassoan** [comment]
@jcfr I had a look at VMTK's build system and it is quite complex. It can be built standalone (using superbuild), as an anaconda Python package, has automated testing (using travis-ci and appveyor), has VTK classes, Python script, examples, and tests. It is a perfect example of a VTK "remote module" of realistic size and complexity. As such, it would be an ideal candidate for your effort of making VTK remote modules available as Python packages.

Having VMTK in Slicer is critical for SlicerHeart, as several modules requires it. The problem now is that VMTK is only available for Slicer Stable Release, but all Slicer core fixes and improvements are only available in Slicer Preview Release.

**Comment by jcfr** [comment]
Agreed. Next week I plan work on building vtk module as python wheels.

**Comment by mikebind** [comment]
Any updates on this?  I also now need bug fixes which are present in the preview but not the stable, and VMTK, which is available in the stable but not the preview.   It seems like I might need to learn to build the Slicer stable (so VMTKworks) but include the key C++ modifications from the preview release so I can avoid crashes I was running into in the stable and which have since been fixed. I'm sure this is not a big deal for super-users, but it feels quite daunting for me.  If the VMTK extension is likely to be out of availability for a while, are there other work arounds you would suggest?

**Comment by lassoan** [comment]
This is inconvenient for many users who rely on VMTK, but it is just a temporary delay.

We had to push this task by a few weeks because @jcfr who is the key expert was called to work on an other urgent task. He is expected to return to this task next week and complete it within two weeks.

**Comment by mikebind** [comment]
Thanks for the update!  I'll turn my attention to other projects for a few weeks.

**Comment by lassoan** [comment]
@jcfr thanks for working on this. It seems that there is still a build error:

https://slicer.cdash.org/viewBuildError.php?buildid=2314968

**Comment by jcfr** [comment]
> It seems that there is still a build error:

Indeed, this is related to the the use of `#warning` not available on windows with visual studio ... see https://github.com/vmtk/vmtk/pull/372/commits/bdddd70cc2ed40a10ba85bff1279d910db31fc1e#diff-417cbf41ad94a4c2b3cfb63043cdee36922cadeb8bf53d6babcf594da5685063

I will instead exit early and display a message on stderr

**Comment by lassoan** [comment]
Thank you!

Note that the macOS build fails, too, for some other reason.

**Comment by jcfr** [comment]
> macOS build fails

This was due to the soon to be replaced extension server ... 

> windows

Issues have been fixed in https://github.com/vmtk/SlicerExtension-VMTK/pull/33

**Comment by lassoan** [comment]
Thank you @jcfr, the module is available in the extensions manager now!
