### ISSUE TITLE
Improve Centerline metrics module

### ISSUE THREAD

**Issue by lassoan** [vmtk/SlicerExtension-VMTK#35]
This is a follow-up to improve features introduced in https://github.com/vmtk/SlicerExtension-VMTK/pull/32

- [ ] "Segmentation" section should be renamed to Cross-section area measurement
- [ ] "Surface area" should be renamed to "Cross-sectional area"
- [ ] "Derived diameter" should be renamed to "Circular equivalent diameter"
- [ ] "VMTK" diameter should be renamed to "Minimum inscribed sphere diameter" (or MIS diameter for short, and put the full word in tooltip). Difference and ratio compared to circular equivalent diameter should be made more clear. For example, a complete line could look like this: `MIS diameter: 16.80mm (CE diameter +2.4mm, +18%)`
- [ ] Allow using centerline curve as centerline input (as opposed to just model nodes). In Slicer Preview Releases, the MIS radius values are saved in the curve node (can be used for coloring, saved in the markups json file, etc.) and can be accessed as a numpy like this: `a=slicer.util.arrayFromMarkupsControlPointData(curveNode, 'Radius')`
- [ ] Allow using model node as input for cross-section area measurement instead of just segmentation node, if it can be easily made work with surface models (e.g., we don't rely on labelmap representations).
- [ ] Computation of cross-sections does not seem to be very robust: spacing between planes is quite large, non-uniform, and their orientation is changing quite randomly. The degree of these problems may depend on the resolution of the input mesh. For example for the mesh in this scene, things are quite bad: https://1drv.ms/u/s!Arm_AFxB9yqHxfZSIMXrFc2FDfTe8Q?e=XYC420 (see image below)

![image](https://user-images.githubusercontent.com/307929/128756086-7922a866-4cc1-4121-9cee-c2631b05b8c4.png)

**Comment by chir-set** [comment]
OK, I'll do these one by one.

As for spacing and orientation of cross-sections, it's all dependent on the available points of the centerline model. Perhaps it will be nicer with points of a centerline curve, remains to be seen.

Thanks.

**Comment by lassoan** [comment]
The centerline curve can be resampled smoothly and uniformly. I think measurements (such as MIS radius) are nicely interpolated, too.

**Comment by chir-set** [comment]
Are you sure radii are those of 'Minimum inscribed sphere' at a point ?

According to http://www.vmtk.org/tutorials/BranchSplitting.html , it's rather 'Maximum inscribed sphere'. The latter seems more logical as minimum is next to zero from a centerline point.

**Comment by lassoan** [comment]
Yes, sorry, I meant maximum inscribed sphere.

**Comment by lassoan** [comment]
These are all implemented in the new "Cross-section analysis" module (that was created by merging it with Centerline metrics module).
