### ISSUE TITLE
Merge Centerline metrics and Cross-section analysis modules

### ISSUE THREAD

**Issue by lassoan** [vmtk/SlicerExtension-VMTK#36]
There is significant overlap between features of Centerline metrics and Cross-section analysis modules. The two modules should be merged into one module to combine their strengths and reduce maintenance workload.

**Comment by lassoan** [comment]
@chir-set it would be great if you could work on this, too.

**Comment by chir-set** [comment]
I agree, will be done ASAP, won't be in the coming days however.

**Comment by chir-set** [comment]
Hi @lassoan ,

I'm working on 'Centerline metrics' again to make it work with a freely drawn markups curve, one that does not originate from 'Extract centerline'. I hope it's the final touch in the process of merging 'Cross-section analysis'.

Please review the code [here](https://github.com/chir-set/SlicerExtension-VMTK).

Basically, it adds a 'Radius' measurement from a freely drawn markups curve with all values set to 0.0. It's the simplest approach I've thought of. There are much fewer conditionals to add in many places, and is hence less confusing. Obviously, the module is modifying an input. I suspect high-level devs may object to this.

Please let me know how you would welcome this approach. If you're comfortable with this, I'll then submit a pull request.

Regards.

**Comment by chir-set** [comment]
Hi @lassoan ,

Could you have a look at this [comment](https://github.com/vmtk/SlicerExtension-VMTK/issues/36#issuecomment-913825752) ?

Thanks.

**Comment by lassoan** [comment]
I started to review the code so that I can give a meaningful answer and found a couple of issues (parameter node not working, not polished GUI, etc.) and did not get to review what the best design would be to handle presence/absence of radius measurement.

Adding an all-zero array of radius measurement is very intrusive and misleading change. Adding an array when you actually not have radius measurements is bad because then how would you know that you actually have radius measurements or not? Adding an array with invalid/irrelevant values does not impact just this module, but all the other modules that use scalars. Setting (borderline) invalid 0 radius values in the array is even worse, because it makes 0 radius values much more frequent and so all modules that use radius arrays would need to be prepared to handle this. I'll finish this up and commit this later today.

Most likely adding a few if/else branches to use radius values if available but not break when they are absent would be much easier than adding a fake radius array and deal with all its consequences in this and many other modules. So, don't add an all-zero array.

**Comment by chir-set** [comment]
> how would you know that you actually have radius measurements or not?

This [function](https://github.com/chir-set/SlicerExtension-VMTK/commit/5b2754334b45952c0b8e7761e47947990a2d88e8#diff-c39a669c3c0481381d9d0a4981f9db5bc7c20ba4de5aa85f3c1ac9b2df9d062fR709) would say it, looking for an attribute whose name is a keyword.



> but all the other modules that use scalars.

I agree I did not consider this.

**Comment by lassoan** [comment]
I've committed my changes, so you can continue from here, I don't plan to make further changes for now.

**Comment by chir-set** [comment]
I'm moving in the right way without modifying the curve with invalid radius. Please see the last [commit](https://github.com/chir-set/SlicerExtension-VMTK/commit/e6833c6e1d79075f01aa8e0c07bd37925e9bbc06).

But I noticed a problem with GetCurveLengthWorld(), it does not seem to give reliable distances between points.

>>> for i in range(10):
...          print(i, c.GetCurveLengthWorld(0, i))
... 
0 0.0
1 0.0
2 0.07506109697677789
3 0.2888205943138029
4 0.6248953154166029
5 1.0680242471582944
6 1.604426228045301
7 2.2221322033316673
8 2.911470055488622
9 3.6655937129982292
>>> 


>>> for i in range(3, 10):
...          print(i, c.GetCurveLengthWorld(3, i))
... 
3 0.9795309126286982
4 1.5972368879150642
5 2.2865747400720187
6 3.0406983975816257
7 3.856161927227453
8 4.7334783378161305
9 5.675083055081725
>>> 

Am I reading it wrong ?

In the first case, point 1 should not have been at 0.0 from point 0.
In the second case, point 3 should have been at 0.0 from itself.

I'm leaving this [line](https://github.com/chir-set/SlicerExtension-VMTK/blob/e6833c6e1d79075f01aa8e0c07bd37925e9bbc06/CenterlineMetrics/CenterlineMetrics.py#L384) as such pending clarification.

**Comment by lassoan** [comment]
You are onto something! I think I've called `GetCurveLengthWorld` method incorrectly.

See its documentation:
```
  /// Get length of the curve or a section of the curve.
  /// \param startCurvePointIndex length computation starts from this curve point index
  /// \param numberOfCurvePoints if specified then distances up to the first n points are computed.
  ///   If <0 then all the points are used.
  /// \return sum of distances between the curve points, returns 0 in case of an error
  double GetCurveLengthWorld(vtkIdType startCurvePointIndex=0, vtkIdType numberOfCurvePoints=-1);
```

I think the correct answer should have been this:

```
if self.logic.relativeOriginPointIndex <= pointIndex:
  distanceFromOrigin = self.logic.inputCenterlineNode.GetCurveLengthWorld(self.logic.relativeOriginPointIndex, pointIndex-self.logic.relativeOriginPointIndex)
else:
  distanceFromOrigin = -self.logic.inputCenterlineNode.GetCurveLengthWorld(pointIndex, self.logic.relativeOriginPointIndex-pointIndex)
```

or

```
if self.logic.relativeOriginPointIndex <= pointIndex:
  distanceFromOrigin = self.logic.inputCenterlineNode.GetCurveLengthBetweenStartEndPointsWorld(self.logic.relativeOriginPointIndex, pointIndex)
else:
  distanceFromOrigin = -self.logic.inputCenterlineNode.GetCurveLengthBetweenStartEndPointsWorld(pointIndex, self.logic.relativeOriginPointIndex)
```

**Comment by chir-set** [comment]
@lassoan 

GetCurveLengthBetweenStartEndPointsWorld has been the solution.

I pushed the last [commits](https://github.com/chir-set/SlicerExtension-VMTK/commit/41da838e277bf365984f43c52a6718d77502a6e7).

This module seems at its best now. I'll send the pull request upon your approval.

**Comment by lassoan** [comment]
Sounds great, thank you!

I'm wondering which name we should use. I somewhat prefer "Cross-section analysis" as it is mostly about analyzing the cross-section rather than just a curve. What do you think about using the "Cross-section analysis" name for the module?

**Comment by chir-set** [comment]
> What do you think about using the "Cross-section analysis" name for the module?

I think it's more relevant indeed. There'll be much refractoring required, and prevent conflicts with the existing "Cross-section analysis" module.

I can do the refraction. SlicerVMTK would have to be cleaned of "Cross-section analysis" before pushing.

How do we proceed ?

**Comment by lassoan** [comment]
If yes, then we could simply rename CenterlineMetrics.py and .ui module to CrossSectionAnalysis.* (and in the files replace CenterlineMetrics by CrossSectionAnalysis) and overwrite the current Cross-section analysis module files, then remove the Centerline metrics module.

If the module is not compatible with the current Slicer Stable Release then I can create a separate 4.11 branch in the SlicerExtension-VMTK repository where we could keep the old versions of these modules.

**Comment by chir-set** [comment]
> then I can create a separate 4.11 branch in the SlicerExtension-VMTK repository

I think this should be done, as I doubt functions like GetCurveLengthBetweenStartEndPointsWorld exist in older Slicer releases. Markups objects have been much worked on in the previous month.

I'm starting the rename and refractor and will point you to my fork when done.

**Comment by chir-set** [comment]
Rename of 'Centerline metrics' to 'Cross-section analysis' is now completed in my [fork](https://github.com/chir-set/SlicerExtension-VMTK).
If it's OK for you, I'll send the pull request.

**Comment by lassoan** [comment]
Awesome, please submit the pull request. Thank you.
