### ISSUE TITLE
Extracting centerline on small segments may crash Slicer when decimation aggressiveness is reduced

### ISSUE THREAD

**Issue by chir-set** [vmtk/SlicerExtension-VMTK#41]
When working on segments of small diameter (< 6 mm), If decimation aggressiveness is reduced to 1.0 k, Slicer crashes constantly.

Decimation aggressiveness can be as low as 0.1 k and centerline extraction will succeed on large segments (e.g. an aortic aneurysm.

Please see original report [here](https://discourse.slicer.org/t/extract-centerline-may-crash-slicer-on-tight-arterial-stenosis/19484), with a backtrace and sample scene MRB link.

**Comment by lassoan** [comment]
Most likely this fix solved the problem: https://github.com/Slicer/Slicer/commit/396c8e5d0ac6bcacf413103c3cb358211a9d5d8c

(see more details in https://discourse.slicer.org/t/extract-centeline-auto-detect-tree-mode/26576/7?u=lassoan)
