### ISSUE TITLE
Document Cross-section analysis module

### ISSUE THREAD

**Issue by lassoan** [vmtk/SlicerExtension-VMTK#43]
Add at least a few sentences and 1-2 screenshots about the fully reworked Cross-section analysis module.

**Comment by lassoan** [comment]
@chir-set would you give this a try? Also, I've sent you an invitation to join this repository, please open this page and accept the invitation: https://github.com/vmtk/SlicerExtension-VMTK/invitations

**Comment by chir-set** [comment]
Sorry. I found your message quite late last night. I 'll certainly update the online Reame.md at the link pointed to in CrossSectoonAnalysis.py ASAP. 

As for the invitation, it was expired on accepting today.  What 's the object of the invitation?

**Comment by chir-set** [comment]
@lassoan 
The online [documentation](https://github.com/chir-set/CenterLineMetrics) is updated.

It would be reasonable to move it from my repository, to an official one. I would then delete my repositories, that of former 'Centerline metrics', and that of former 'Cross-section analysis'. This may avoid confusion to users. What do you think ?

**Comment by chir-set** [comment]
Concerning documentation, if the README.md file lies at 

SlicerExtension-VMTK/tree/master/CrossSectionAnalysis/README.md,

would pointing to

https://github.com/vmtk/SlicerExtension-VMTK/tree/master/CrossSectionAnalysis/

just show its content ?

This would simplify moving the documentation in a single place.

TIA.

**Comment by lassoan** [comment]
See here: https://github.com/vmtk/SlicerExtension-VMTK/blob/master/Docs/CrossSectionAnalysis.md
