### ISSUE TITLE
Cannot Place Fiducial

### ISSUE THREAD

**Issue by adamgranthendry** [vmtk/SlicerExtension-VMTK#44]
### Problem:

I cannot place fiducials on my 3D STL model for extracting centerlines. Please let me know if I am performing a step incorrectly.

### System:

**OS:** Windows 10
**3D Slicer:** 4.10.2

### Steps to Reproduce

1. Choose file to add  (`data.stl`)
![image](https://user-images.githubusercontent.com/77850046/133849893-3a8f2661-6fca-49fe-99c2-f908159b02bf.png)

2. Load the data as a `Model`
![image](https://user-images.githubusercontent.com/77850046/133850043-d9a23ffc-f6d5-40cc-a4da-ae89217bb3e2.png)

3. Convert Model to Segmentation Node

![image](https://user-images.githubusercontent.com/77850046/133850270-e31d9c48-5487-431e-a818-eec29ac8098c.png)

4. Open the Centerline Computation module

![image](https://user-images.githubusercontent.com/77850046/133850415-37a4848e-9c43-4ed4-9b69-91a5b87772a7.png)

5. Choose `data` as the `Vessel tree model` and choose `Create new MarkupsFiducial`

![image](https://user-images.githubusercontent.com/77850046/133850574-89470319-ab7f-4b70-b1b5-c18fe03c45a1.png)

6. Fiducial does not appear when attempting to add to model

**Comment by lassoan** [comment]
VMTK extension in Slicer-4.10.2 was very rudimentary. Please use latest Slicer Preview Release or latest Slicer Stable Release.

**Comment by adamgranthendry** [comment]
@lassoan As I said, I STARTED with the master release, and this happend. I went from master, to stable, all the way down to 4.10 and gave up. None of these have worked for me.

Are any of the steps I have presented incorrect?

**Comment by lassoan** [comment]
I've just tested on Windows 10, installed latest Slicer Stable Release and latest Slicer Preview Release, installed VMTK extension, tested on a simple mesh, all worked perfectly. What exactly went wrong with Slicer-4.11 2021-02-26 or Slicer-4.13-2021-09-16?

**Comment by adamgranthendry** [comment]
Quite literally, the fiducials do not appear anywhere on the model. If I try to run the module after placing fiducials, Slicer simply closes without any warnings.

**Comment by lassoan** [comment]
The discussion is moved to https://discourse.slicer.org/t/vtkm-extension-cannot-place-fiducial/19735
