### ISSUE TITLE
Review request : CrossSectionAnalysis - parallel surface area calculation in C++

### ISSUE THREAD

**Issue by chir-set** [vmtk/SlicerExtension-VMTK#47]
Hi,

This [branch](https://github.com/chir-set/SlicerExtension-VMTK/tree/TryCppCrossSection) uses multi-threading for parallel cross-section area calculation in C++.

I hereby request a code review by core developers, with an ultimate goal of merging an improved patch in SlicerVMTK.

The code in this branch is called from Python, calculates cross-section areas at each point of a centerline in parallel joinable threads, and updates the output table of CrossSectionAnalysis accordingly.

It is intended to accelerate the 'UpdateTable' step of this module.

As for efficiency, computation time may decrease from 20 secs to 6 secs with a centerline model having 2500 points.

Unfortunately, it constantly fails with vtkMRMLMarkupsCurveNode centerlines. Any call to any function of a curve leads to a crash. Please advise for a fix.

If at some point, everything being fixed and improved, you deem it's a valuable addition to CrossSectionAnalysis, I'll be glad to submit a pull request.

Thank you for any suggestions.

@lassoan

**Comment by lassoan** [comment]
Thank you for working on this. I've added some comments to your branch, which might help moving forward a bit. I'm closing this issue now, as it makes things much more clear if you submit a pull request with your proposed changes. . You can mark a pull request as "draft" if it is not ready for integration but still a work in progress.
