### ISSUE TITLE
VMTK can't be loaded

### ISSUE THREAD

**Issue by lushiyu1997** [vmtk/SlicerExtension-VMTK#58]
I download the 3D slicer and install SlicerVMTK from Extension Manager according to the guide, 
but find 'vtkvmtk module is not loaded' in Module finder and unable to use vessel toolkits.
software version：4.11 & win10 .
Thanks in advance.

**Comment by lushiyu1997** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/73114318/158643825-508e9263-4b91-4d6a-833c-0a2a66f10a61.png">
Sorry ,still not work ..

**Comment by lassoan** [comment]
I see, that is not an actual error. See details here: https://github.com/vmtk/SlicerExtension-VMTK/issues/22
