### ISSUE TITLE
Cross-section analysis : improve cross-section area measurement method ?

### ISSUE THREAD

**Issue by chir-set** [vmtk/SlicerExtension-VMTK#75]
Hi @lassoan,

This concerns determining the cross-section area around the centerline in 'Cross-section analysis' module.

Initially, I used SetExtractionModeToClosestPointRegion so as to eliminate the area of branches in the section plane.

I realised that around the centerline itself, i.e., in the region of interest, the side-effect of this method may lead to the selection a very tiny area which may in fact correspond to a hole in the segment. This is very detrimental as the minimum CE diameter will point to this.

I propose to use SetExtractionModeToAllRegions instead. This implies that the user does not feed in branched segments. It can be precised in tooltips and in the documentation page. Branches imply too large areas being calculated, from parts not around the centerline. In the zone of interest itself, holes and wall spiculas get eliminated and are not included in the section surface. The picture below (a mock-up) describes this rationale for the proposed change. (Please note that infra-millimetric holes are included by the triangulator nevertheless).It is done using SetExtractionModeToAllRegions. With ClosestPointRegion, either the hole or the spicula would have been selected.

![CrossSectionAnalysisChangeRationale](https://user-images.githubusercontent.com/33979252/218436832-e528ff1b-ff0f-4229-941a-7bd37f4bec66.png)

It would be also an option to propose ClosestPointRegion or AllRegions in the UI.

I can of course make the changes if you deem it worthwhile.

Regards.

**Comment by chir-set** [comment]
OK then, things are left untouched. Thanks.

**Comment by lassoan** [comment]
Maybe just add a note to the module documentation that the segmented blood should not contain internal holes.

**Comment by lassoan** [comment]
For vascular applications, measuring the area of the main branch is probably always the preferred method.

If people use the module for other purposes then measuring the total cross-section may be useful, too. However in that case the holes would be counted twice, so we would need to use vtkContourTriangulator to get the correct surface area (or an even more robust - but somewhat less accurate - method: measure the surface area by counting the number of non-zero voxels in the oblique slice that cuts through the segmentation).
