### ISSUE TITLE
How to execute the source code of  the SlicerExtension-VMTK in pycharm?

### ISSUE THREAD

**Issue by chuanqiWen** [vmtk/SlicerExtension-VMTK#77]
How should I execute the source code of the  SlicerExtension-VMTK. I can't import vtkvmtkDifferentialGeometryPython.

**Comment by lassoan** [comment]
It is a shared library with dependencies on VTK and other libraries. You need to choose `PythonSlicer` as interpreter to be able to load it.

Unfortunately, PyCharm's skeleton (a.k.a stub) generation for shared libraries is buggy - in most PyCharm versions it doesn't work. So you'll only get documentation and auto-complete if you connect with the debugger. We are in the process of generating stub files for Slicer and eventually for extensions, too (see https://github.com/Slicer/Slicer/issues/6875).
