### ISSUE TITLE
VMTK error with 4.6.2 Slicer

### ISSUE THREAD

**Issue by marly892** [vmtk/SlicerExtension-VMTK#8]
hello,

I Installed VMTK extension on 3DSlicer (version 4.6.2) but there is an error which does not allow me to see the drop-down menu I can see in the video tutorial.

this is what I get trying to open the 'centerline Computation' VMTK option
Switch to module:  "CenterlineComputation" 
Traceback (most recent call last):

  File "/home/marlene/.config/NA-MIC/Extensions-25516/SlicerExtension-VMTK/lib/Slicer-4.6/qt-scripted-modules/CenterlineComputation.py", line 89, in setup
    self.__seedFiducialsNodeSelector.markupsSelectorComboBox().noneEnabled = False
AttributeError: qSlicerSimpleMarkupsWidget has no attribute named 'markupsSelectorComboBox'

thank you for any suggestion

Marlene

**Comment by lassoan** [comment]
Please try it with the latest nightly version of Slicer and let us know id it works.

**Comment by marly892** [comment]
thank you very much
it works
