### ISSUE TITLE
How to convert the coordinates of the output center line to the Cartesian coordinate system in the original image file?

### ISSUE THREAD

**Issue by wt812549723** [vmtk/SlicerExtension-VMTK#84]
I want to draw such a centerline in the original image file (.nii), so I need to get the coordinate position of the centerline in the original image file. However, the obtained coordinate position does not seem to be in the Cartesian coordinate system of original image via provided codes
![QQ图片20230402171630](https://user-images.githubusercontent.com/65691801/229343826-e32d0047-420e-4c7b-aef6-eec00329a77c.png)
.

**Comment by lassoan** [comment]
You can transform physical coordinates to voxel coordinates by multiplying with the LPS to IJK matrix that is stored in the image header. Nifti uses a very complicated and redundant way to store this matrix, so I would recommend to use NRRD file format instead.
