### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by swtb3** [vmtk/SlicerExtension-VMTK#87]
Is it possible to use this extension in a more traditional pythonic way? 
My existing working is using numpy, but methods like the centreline computation would be really useful to me. Though it doesnt seem as simple as "from slicer-vmtk import centreline_computation"

Any guidance would be much appreciated.

**Comment by lassoan** [comment]
Yes, sure, you can use it any way you want. For example:

```python
import ExtractCenterline
logic = ExtractCenterline.ExtractCenterlineLogic()
logic....
```

I'm closing this as we use the issue tracker for tracking problems. Please use the [Slicer forum](https://discourse.slicer.org) for asking questions about how to use this extension.
