### ISSUE TITLE
centerline computation

### ISSUE THREAD

**Issue by marly892** [vmtk/SlicerExtension-VMTK#9]
hello :)

I am using the VMTK centerline computation module to extract the centerlines of brain vessels. I also read that the information about the vessel ray, at each point along the centerline, should be one of the output  but I cannot find it. Moreover I am not able to visuallize the Voronoi model like it is shown in the tutorials.

thank you for any suggestion

Marlene

**Comment by lassoan** [comment]
I think the Voronoi model contains the "rays". What do you mean by you are not able to visualize the Voronoi model? What do you do? What do you expect to happen? What happens actually?

**Comment by marly892** [comment]
I can visualise the 'center line' and the  'center line end points' correctly but I don't know how to extract the "rays " from the voronoi model . I have tried to save it in a folder in order to open it but it seems to exist just inside Slicer.

**Comment by lassoan** [comment]
In what file format did you try to save the Voronoi model? Can you attach a saved file?

**Comment by lassoan** [comment]
Have you clicked "Start" after preview? Voronoi model is not computed when you only generate preview.

**Comment by marly892** [comment]
I succeded in opening it but the only informations I can get are the position of the points of the Voronoi model and a vector called 'faces'. Not sure how calculate the rays.

thank you again

**Comment by lassoan** [comment]
There is a point data array called "Radius" that contains the radius for each point.

**Comment by lassoan** [comment]
It seems that the issue has been solved, there were no more questions.
