### ISSUE TITLE
Fix build failure on Windows

### ISSUE THREAD

**Issue by chir-set** [vmtk/SlicerExtension-VMTK#91]
Hi @lassoan,

Following #85, SlicerVMTK [fails](https://slicer.cdash.org/viewBuildError.php?buildid=3113778) to build for Windows. I fixed one trivial issue in #90. The other build failures are specific to Windows and are out of reach to me.

Can you please have a look as you proposed in #85?

Thank you.

**Comment by chir-set** [comment]
I understand you are very busy @lassoan, this is just a kind reminder.

I made a second change in #92 and there are still remaining errors. I suspect  that 

`class vtkCrossSectionCompute`

should be updated to 

`class VTK_SLICER_CROSSSECTION_COMPUTE_EXPORT vtkCrossSectionCompute.`

I don't have any means to do a Windows build, and it's not right to pollute the PR history with guessed pseudo-fixes.

One solution to resume the failing build is to revert the blocking commits, at least SlicerVMTK will be available for all systems. Reverting will be the last solution in a reasonable delay.

Regards.

**Comment by lassoan** [comment]
Thanks for the fix, it looks good, but I'll test it before the next nightly build starts.

**Comment by chir-set** [comment]
Thank you for this commit, it now builds on all 3 systems.

I committed #93 to rightly import the extruded logic. It should run everywhere now.

Regards.
